name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          registry-url: https://registry.npmjs.org/
      
      - name: Bump version
        uses: MeilCli/bump-release-action@v2
        with:
          bump: ${{ github.event.inputs.bump }}
